### ISSUE TITLE
运行不了soga

### ISSUE THREAD

**Issue by chen63536** [sprov065/soga#1]
● soga.service - soga Service
   Loaded: loaded (/etc/systemd/system/soga.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2020-05-10 06:43:55 UTC; 8s ago
  Process: 21964 ExecStart=/usr/local/soga/soga (code=exited, status=255)
 Main PID: 21964 (code=exited, status=255)

May 10 06:43:55 vultr.guest soga[21964]: File "start.py", line 466, in main
May 10 06:43:55 vultr.guest soga[21964]: File "start.py", line 249, in start_for_sspanel
May 10 06:43:55 vultr.guest soga[21964]: File "panel/mod_mu.py", line 210, in get_node_info
May 10 06:43:55 vultr.guest soga[21964]: File "panel/mod_mu.py", line 36, in panel.mod_mu.PanelNode.__init__
May 10 06:43:55 vultr.guest soga[21964]: File "panel/mod_mu.py", line 41, in panel.mod_mu.PanelNode.__parse_server
May 10 06:43:55 vultr.guest soga[21964]: Exception: Can not parse server: 45.76.239.215
May 10 06:43:55 vultr.guest soga[21964]: [21965] Failed to execute script main
May 10 06:43:55 vultr.guest systemd[1]: soga.service: main process exited, code=exited, status=255/n/a
May 10 06:43:55 vultr.guest systemd[1]: Unit soga.service entered failed state.
May 10 06:43:55 vultr.guest systemd[1]: soga.service failed.

**Comment by sprov065** [comment]
过一段时间发布
