### ISSUE TITLE
[bug反馈]Trojan对接V2board面板成功，但无法完成订阅。

### ISSUE THREAD

**Issue by cameronx** [sprov065/soga#10]
具体情况是Trojan对接V2board成功，蓝灯亮起，soga后端显示运行正常。但是V2board面板上的订阅复制到Trojan-QT5客户端中无法连接。请问这是为什么呢？

**Comment by cameronx** [comment]
补充说明 将订阅链接复制到Clash客户端中可以正常连接 但是Trojan-QT5客户端不行

**Comment by sprov065** [comment]
提供trojan-qt5的详细配置截图，基本上就是客户端配置不对

**Comment by cameronx** [comment]
![微信截图_20200628115715](https://user-images.githubusercontent.com/1542855/85937602-b0df8580-b937-11ea-9dc1-9478541a4e50.png)
![微信截图_20200628115736](https://user-images.githubusercontent.com/1542855/85937606-b4730c80-b937-11ea-84c9-1e825b3780fc.png)
![微信截图_20200628120330](https://user-images.githubusercontent.com/1542855/85937610-b6d56680-b937-11ea-9068-fa68a4d85d4c.png)
![微信截图_20200628120616](https://user-images.githubusercontent.com/1542855/85937624-cfde1780-b937-11ea-85ce-03a23b089586.png)
![微信截图_20200628120654](https://user-images.githubusercontent.com/1542855/85937627-dcfb0680-b937-11ea-90f9-ed661b7387f8.png)
烦请您看一下，真的不知道哪里设置错了...

**Comment by cameronx** [comment]
此外就是IOS端 使用shadowrocket也无法链接
