### ISSUE TITLE
希望可以添加对malio的支持

### ISSUE THREAD

**Issue by qd201211** [sprov065/soga#12]
soga对接malio会有不扣除流量的问题（流量统计却是正常），使用其他付费后端没出现此问题。

**Comment by sprov065** [comment]
使用的对接方式是webapi还是数据库，是否都有这个问题

**Comment by qd201211** [comment]
> 使用的对接方式是webapi还是数据库，是否都有这个问题

我使用的是数据库对接，webapi我没对接成功

**Comment by sprov065** [comment]
已更新

**Comment by qd201211** [comment]
> 已更新

已重新尝试对接，流量扣除正常。但审计规则好像生效但是不记录，不知是否可以修复。谢谢作者

**Comment by qd201211** [comment]
> > 已更新
> 
> 已重新尝试对接，流量扣除正常。但审计规则好像生效但触发后不进行记录，不知是否可以修复。谢谢作者

审计已正常工作~
