### ISSUE TITLE
自定义 v2ray 的 routing 和 outbond

### ISSUE THREAD

**Issue by phlinhng** [sprov065/soga#14]
某些场景（例如流媒体解锁）会用到自定义 outbound 的功能。soga 是否有计划加入这项支持？

**Comment by sprov065** [comment]
dns流媒体解锁已安排上进程，自定义outbound这部分可能比较慢，因为soga完全是从0开始编写的，而不是利用v2ray-core在其基础上进行修改。

**Comment by jinwyp** [comment]
还有一个问题需要  outbound  和 routing 就是google 总是跳出验证码 可以通过 这个解决 让google 走 ipv4

不知道soga 怎么处理
