### ISSUE TITLE
ws;tls死活不行tls;ws就可以

### ISSUE THREAD

**Issue by bigccc** [sprov065/soga#15]
ws;tls死活不行tls;ws就可以

难道是wiki写错了？？？

**Comment by sprov065** [comment]
不知道你说的哪里可不可以，有些版本的面板确实ws和tls的顺序处理不太一样，根据你自己的实际情况调整

**Comment by bigccc** [comment]
就是在sspanel面板添加节点那里面。

通过调整顺序已经解决。

谢谢！

发件人: sprov<mailto:notifications@github.com>
发送时间: 2020年7月14日 9:01
收件人: sprov065/soga<mailto:soga@noreply.github.com>
抄送: bigccc<mailto:scww@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [sprov065/soga] ws;tls死活不行tls;ws就可以 (#15)


不知道你说的哪里可不可以，有些版本的面板确实ws和tls的顺序处理不太一样，根据你自己的实际情况调整

―
