### ISSUE TITLE
建议 默认申请 ecc 证书；最低支持 TLS 1.2

### ISSUE THREAD

**Issue by phlinhng** [sprov065/soga#17]
为了避免未来升级麻烦，而且现在大多数操作系统皆己支持 ecc，建议内建证书模块可以默认申请 ecc 证书。另外为了安全考量，可以考虑禁用 tls 1.2 以下版本，仅支持 tls 1.2 以上的加密协议。

**Comment by sprov065** [comment]
今天更新支持ecc证书，强制最低tls1.2一般不需要这么做，v2ray客户端默认会选择最新的tls版本，强制限制的话反而会成为特征
