### ISSUE TITLE
按照教程配置成功，但是使用V2RayN连接报错

### ISSUE THREAD

**Issue by missway** [sprov065/soga#19]
使用V2board 面板配置WS-TLS连接，V2RayN报错结果如下：
[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://ladder.andyliang.in/0qBE): 404 Not Found > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/07/22 13:08:51 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2020/07/22 13:08:52 [Info] [764936043] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/07/22 13:08:52 [Info] [764936043] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe

**Comment by colorfulshadowty** [comment]
我也是这个问题，ios端就可以使用
请问一下解决了吗
