### ISSUE TITLE
希望出个docker镜像

### ISSUE THREAD

**Issue by VeryAdd** [sprov065/soga#2]
希望出个docker镜像，这样学习的时候配置可以更方便些。
我的意思是 在有时候出现莫名其妙的问题或者配置失误的时候可以通过删除镜像来重新安装。
而不至于说要系统重装来解决。。

**Comment by sprov065** [comment]
soga 命令有卸载选项，会完全卸载，不会有残留

docker以后也会加上

**Comment by VeryAdd** [comment]
嗯嗯，soga和v2-ui应该不能共存吧？
不能的话 去开一台新的试试看

**Comment by sprov065** [comment]
没有冲突
