### ISSUE TITLE
soga后端，v2board前端使用quanlimultx订阅显示500错误

### ISSUE THREAD

**Issue by cyril-cheng** [sprov065/soga#21]
之前使用soga后端，配置成trojan的时候quanlimultx订阅会显示status code 500错误，v2ray正常。今天quantumult更新以后都成500错误了。去v2board群里问了，他们使用Aurora和Tidalab-trojan官方后端的表现都是正常的。

**Comment by sprov065** [comment]
订阅从来没跟后端有关系，你要不把后端停了再试试吧
