### ISSUE TITLE
无法统计用户在线与使用流量

### ISSUE THREAD

**Issue by HtnrxUNc** [sprov065/soga#22]
对接v2board前端，对接目前应该是没什么问题，目前无法获得用户在线状态及用户已使用流量。

**Comment by sprov065** [comment]
因为v2board机制限制，数据库对接不支持用户在线数量以及节点在线状态，但是流量肯定可以统计的

**Comment by HtnrxUNc** [comment]
> 因为v2board机制限制，数据库对接不支持用户在线数量以及异步在线状态，但是流量肯定可以统计的

采用的是api方式对接。流量统计功能目前异常，是否有可能是权限问题？需要去目录下重新赋予755权限？

**Comment by sprov065** [comment]
那我不清楚了，你也没有提供任何有用的信息

**Comment by sdd-cn** [comment]
webapi_mukey=xxxx

**Comment by HtnrxUNc** [comment]
> 那我不清楚了，你也没有提供任何有用的信息

目前功能已经正常，猜测是权限问题，将前端目录赋予777权限和www:www所有者后功能正常
