### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by VeryAdd** [sprov065/soga#3]
再一台全新的机器上安装了您的程序，可让人绝望的是它却无法运行。
![image](https://user-images.githubusercontent.com/22927845/82575194-b7514380-9bba-11ea-96da-95649e72b735.png)

期间我尝试过了更换系统，赋予777权限等等方法 都无法解决。
而且我也找不到日志文件在哪里。
对了，我所使用的是https://github.com/Anankke/SSPanel-Uim
的dev分支，是我前端选择错误了吗？

**Comment by VeryAdd** [comment]
![image](https://user-images.githubusercontent.com/22927845/82575712-67bf4780-9bbb-11ea-8b23-4b66e97b0fab.png)
对了，这是我前端所填写的地址。
当然图片里的域名并不是这个。。。
后端的域名我托管到了cloudflare 不知道这是不是问题之一？

**Comment by VeryAdd** [comment]
找到原因了，是因为填写tls证书那空着导致的。。。
希望作者可以修复一下

**Comment by sprov065** [comment]
目前不支持自动申请证书，必须要填写
