### ISSUE TITLE
DNS自动申请证书这个坑多的一匹

### ISSUE THREAD

**Issue by gimgoo** [sprov065/soga#31]
如题，DNS自动申请证书这个坑多的一匹。大多数不能启动，少数情况能启动，所以到现在都不知道能启动的是什么情况，不能启动的是什么原因，个人觉得教程写的trojan证书配置过于简单。

该写的cf邮箱跟api key都写了，域名也解析到相应ip了，请问大佬这是什么情况。

![image](https://user-images.githubusercontent.com/31849284/95218815-4471fd80-0827-11eb-95a8-e26e694639c2.png)

**Comment by sprov065** [comment]
我不知道你填的对不对，总之运行的命令给你打印出来了，各种提示给你到位了，自己跑一下命令看看找找原因不是什么难事吧

**Comment by gimgoo** [comment]
> 我不知道你填的对不对，总之运行的命令给你打印出来了，各种提示给你到位了，自己跑一下命令看看找找原因不是什么难事吧

大佬说的对，但是我没去搞，直接换了域名跟系统重装
