### ISSUE TITLE
vmess aead无法使用

### ISSUE THREAD

**Issue by wloot** [sprov065/soga#35]
服务端: soga v2.0.5 with `vmess_aead=true`
客户端: v2rayng 1.4.10 on Android

错误情况: 无法连接. 试了下隔壁v2ray-poseidon和原版v2ray, 没有问题.
同样的情况也可以在v2rayn(Windows)客户端复现

**Comment by sprov065** [comment]
经过测试，最新版 v2rayN&G 与小火箭均无问题，soga 的 VMess AEAD 没有问题，你可能测试方式有误，只有服务端的 alterID 为 0 时才会真正启用 VMess AEAD

**Comment by wloot** [comment]
> 经过测试，最新版 v2rayN&G 与小火箭均无问题，soga 的 VMess AEAD 没有问题，你可能测试方式有误，只有服务端的 alterID 为 0 时才会真正启用 VMess AEAD

目前我这边的情况是这样的: v2rayng 1.4.0及更旧的版本无论alterID设置为0还是非0都是可以正常使用. 在1.4.0以后(https://github.com/2dust/v2rayNG/releases/tag/1.4.1), alterID设置为0即无法连接上, 非0正常.

> 只有服务端的 alterID 为 0 时才会真正启用 VMess AEAD
服务端soga只是打开了`vmess_aead`选项,  不清楚如何手动设置alterID.

**Comment by wloot** [comment]
附上soga配置:
```
type=v2board
server_type=v2ray
node_id=1
soga_key=
api=webapi

webapi_url=<xxx>
webapi_mukey=<xxx>

default_dns=
dns_cache_time=10

v2ray_reduce_memory=false
vless=false
vmess_aead=true

proxy_protocol=true

user_conn_limit=0
user_speed_limit=0
node_speed_limit=0
check_interval=100
force_close_ssl=false
forbidden_bit_torrent=true
auto_update=true
```

**Comment by sprov065** [comment]
v2board 默认alterId就是2，无法更改

**Comment by wloot** [comment]
> v2board 默认alterId就是2，无法更改

Emm.. 有办法通过修改 v2board 发送的配置来启用 VMess AEAD 吗? 看了下`/api/v1/server/deepbwork/config`的响应内容, 似乎没有 alterID 相关的配置.

**Comment by wloot** [comment]
在`/api/v1/server/deepbwork/user`找到了, 再次感谢提点.

**Comment by wloot** [comment]
`alter_id`改成0后, 客户端alterid无论怎么设置都连不上了...

**Comment by sprov065** [comment]
目前并不支持这样的方式改alterid去启用vmessaead
