### ISSUE TITLE
发现了个小问题，。

### ISSUE THREAD

**Issue by nauya** [sprov065/soga#37]
日本煤炉支付时跳转页面，使用服务器  日本樱花 
同一台服务器搭建环境为centos7 使用的均是soga后端  trojan节点无法访问。v2ray节点可以访问（v2ray协议为ws）
反复测试过很多次了 不知道什么问题
但是此情况测试了  shadowrocket  出现这种情况（指trojan无法访问，v2可以访问）
Windows的clash客户端两者都可以访问

下面列出例子
https://payment.sej.co.jp/od/hisp.asp?00229214536376422a66453f83da98b7

**Comment by sprov065** [comment]
大概跟客户端规则有关吧，跟服务端没关系
