### ISSUE TITLE
v2.1.2 Trojan Problem

### ISSUE THREAD

**Issue by wsa01378** [sprov065/soga#39]
环境：HK-VPS soga trojan webapi对接V2BOARD 
老大试试ios小火箭trojan看[无线新闻]APP是否复现
![4df32a8edb808814d90fc22fdb829a4](https://user-images.githubusercontent.com/72466780/102711984-ae635480-42f8-11eb-993c-cd114e488a1e.png)
换v2ray则问题解决

**Comment by sprov065** [comment]
自行检查各种配置项是否有问题

**Comment by sprov065** [comment]
经常有人在 tls 的设置中出错

**Comment by leon7786** [comment]
@sprov065 一样有这问题，你花30秒ios装下就知道了。但仅仅只是那个APP问题
