### ISSUE TITLE
填完webapi地址后会报超过2秒的错误，程序启动不起来

### ISSUE THREAD

**Issue by zihong** [sprov065/soga#4]
填完webapi地址后会报超过2秒的错误，程序启动不起来，请问如何解决

**Comment by sprov065** [comment]
先按配置文件说明进行填写

不行就发 soga 日志

**Comment by zihong** [comment]
请问如何查看soga日志，在哪个目录的文件

**Comment by sprov065** [comment]
soga命令

**Comment by zihong** [comment]
你好，没找到查看日志的命令


soga 管理脚本使用方法:
------------------------------------------
soga              - 显示管理菜单 (功能更多)
soga start        - 启动 soga
soga stop         - 停止 soga
soga restart      - 重启 soga
soga status       - 查看 soga 状态
soga enable       - 设置 soga 开机自启
soga disable      - 取消 soga 开机自启
soga update       - 更新 soga
soga install      - 安装 soga
soga uninstall    - 卸载 soga
------------------------------------------
root@instance-1:~# soga status
● soga.service - soga Service
   Loaded: loaded (/etc/systemd/system/soga.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
root@instance-1:~# /etc/soga/soga.conf
-bash: /etc/soga/soga.conf: Permission denied
root@instance-1:~# vi /etc/soga/soga.conf
root@instance-1:~# soga status
● soga.service - soga Service
   Loaded: loaded (/etc/systemd/system/soga.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
root@instance-1:~# sogo restart
-bash: sogo: command not found
root@instance-1:~# soga restart
soga重启失败，可能是因为启动时间超过了两秒，请稍后查看日志信息

**Comment by sprov065** [comment]
soga status

**Comment by sprov065** [comment]
等更新
