### ISSUE TITLE
如何实现 v2ray的  routing 和 outbond 解决google 验证码问题

### ISSUE THREAD

**Issue by jinwyp** [sprov065/soga#40]
因为要解决google 的频繁出现的验证码问题

v2ray可以 通过  routing 和 outbond 解决 不知道soga 怎么处理这个问题？

https://github.com/v2ray/v2ray-core/issues/308

{
  "inbounds": [
    // your inbouds config
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "domain": [
          "domain:google.com"
        ],
        "outboundTag": "ipv4"
      }
    ]
  },
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "ipv4",
      "sendThrough": "your ip",
      "protocol": "freedom",
      "settings": {}
    }
  ]
}

**Comment by sprov065** [comment]
soga默认就是ipv4解析

**Comment by jinwyp** [comment]
> soga默认就是ipv4解析

也会有让google 用ipv6解析的需求 解决google验证码的问题， soga如何解决？

**Comment by sprov065** [comment]
无，自行更换一个好IP，soga不是v2ray，没有这些配置

**Comment by zzx396** [comment]
同样遇到了这个问题，原来soga默认是IPV4解析啊，怪不得搭建IPV6隧道没有用。
