### ISSUE TITLE
dns.yml 配置 fallback 问题

### ISSUE THREAD

**Issue by mp-s** [sprov065/soga#41]
dns.yml配置了特定域名解析后, 如果该dns服务器不在线, 将会导致该域名访问失败
v2ray-core的dns配置支持fallback, 当设置的解锁dns不在线时可以使用设置的默认dns解析

**Comment by sprov065** [comment]
这会给用户一个错觉，一会解锁流媒体，一会不解锁

**Comment by mp-s** [comment]
请问可否增加可选dns fallback选项的功能, 默认不启用

**Comment by sprov065** [comment]
以下是折中的方式，同一规则下配置多个 dns 地址，前面的 dns 地址挂了按顺序使用下一个 dns 地址，2.1.5 版本会支持：

```
1.1.1.1,2.2.2.2,3.3.3.3:
   - geosite:netflix
```

**Comment by mp-s** [comment]
感谢, 我会静待支持的新版发布
