### ISSUE TITLE
在 Fedora 上配置使用 soga 的问题

### ISSUE THREAD

**Issue by froseiun** [sprov065/soga#42]
Fedora 版本: Fedora Server 33
内核版本: Linux Kernel 5.9.16
Soga 版本: 2.1.5
问题: 当运行安装脚本时提示“请使用 CentOS 7 或更高版本的系统！”
管理脚本存在同样的判断机制，无法正常使用

**Comment by sprov065** [comment]
暂时没适配这个系统
