### ISSUE TITLE
在对接ProxyPanel时遇到一个小问题

### ISSUE THREAD

**Issue by yusheng6b** [sprov065/soga#45]
# webapi 对接
webapi_url=https://xxx.com/                  # webapi url，填写面板主页地址
webapi_mukey=xxxx                            # webapi key

# webapi key 这项该填写什么内容呢，在哪个位置寻找呢，希望大佬给个提示～

**Comment by sprov065** [comment]
webapi_mukey是一开始使用的配置名称，2.1.9版本改成了webapi_key，两者是相同的配置。

2.1.9之后推荐使用webapi_key，不过同时也会兼容旧版本的webapi_mukey，所以旧配置文件也可使用，但在未来可能会移除掉webapi_mukey。
