### ISSUE TITLE
最新版Soga使用V2board对接Trojan无法启动

### ISSUE THREAD

**Issue by Heartbeats1104** [sprov065/soga#46]
升级后按以前版本填写，节点就1个默认id为1，soga无法启动，log报错

`Feb 02 04:14:46 debian soga[2033]: 2021/02/02 04:14:46 Parse node failed: invalid character 'e' looking for beginning of value

Feb 02 04:14:46 debian soga[2033]: 2021/02/02 04:14:46 error code: 1020

Feb 02 04:14:46 debian soga[2033]: 2021/02/02 04:14:46 get node failed: invalid character 'e' looking for beginning of value

Feb 02 04:14:46 debian systemd[1]: soga.service: Main process exited, code=exited, status=255/EXCEPTION

Feb 02 04:14:46 debian systemd[1]: soga.service: Failed with result 'exit-code'.`

**Comment by Heartbeats1104** [comment]
以下是soga配置文件，请问是问题出在哪了？

# 基础配置
listen=80
type=v2board
server_type=trojan
node_id=1
soga_key=

# webapi 或 db 对接任选一个
api=webapi

# webapi 对接信息
webapi_url=xxx
webapi_key=xxx

# db 对接信息
db_host=db.domain.com
db_port=3306
db_name=
db_user=root
db_password=

# 手动证书配置
cert_file=
key_file=

# 自动证书配置
cert_mode=http
cert_domain=域名
cert_key_length=ec-256
dns_provider=

# dns 配置
default_dns=8.8.8.8,1.1.1.1
dns_cache_time=10

# v2ray 特殊配置
v2ray_reduce_memory=false
vless=false
vless_flow=

# tls 配置
tls_alpn=h2,http/1.1
xtls=false

# proxy protocol 中转配置
proxy_protocol=false

# 其它杂项
user_conn_limit=0
user_speed_limit=0
node_speed_limit=0
check_interval=60
force_close_ssl=false
forbidden_bit_torrent=true
log_level=info

# whmcs 对接配置
whmcs_port=80
whmcs_net=ws
whmcs_tls=false
whmcs_alter_id=2
whmcs_ws_path=/
whmcs_rate=1

# 全局限制 IP 配置
redis_enable=false
redis_addr=
redis_password=
redis_db=0
conn_limit_expiry=60

**Comment by sprov065** [comment]
google: error code 1020
