### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by yusimtin** [sprov065/soga#5]
![微信截图_20200526212800](https://user-images.githubusercontent.com/65960235/82906439-d6274f80-9f97-11ea-99d8-c549b64eba87.png)
也不知道是哪儿的问题，就是启动不起来，麻烦大神帮忙指导一下谢谢

**Comment by yusimtin** [comment]
soga.conf是这么填的，其他没改动过
![微信截图_20200526213220](https://user-images.githubusercontent.com/65960235/82906950-92811580-9f98-11ea-9ba7-21f3d22a69b0.png)

**Comment by sprov065** [comment]
webapi_url要带http://或https://

**Comment by yusimtin** [comment]
![微信截图_20200526213220](https://user-images.githubusercontent.com/65960235/82908358-6ebecf00-9f9a-11ea-9229-b084f67891a0.png)
改好了，还是启动不了。。。不知道什么原因，大神可以再指导我一下嘛？

**Comment by yusimtin** [comment]
只需要改这一个文件吗？还是需要再改别的文件，我只改动了这一个文件

**Comment by sprov065** [comment]
面板节点地址

**Comment by yusimtin** [comment]
我的sspanel面板是域名进入的，还是应该填些ip节点地址呢?
我是按照我宝塔s'spanel的config文件填的
![微信截图_20200526213222](https://user-images.githubusercontent.com/65960235/82909087-67e48c00-9f9b-11ea-8bb0-595855d1ae7d.png)

**Comment by sprov065** [comment]
不能先看看wiki吗

**Comment by zongxinqian** [comment]
> ![微信截图_20200526212800](https://user-images.githubusercontent.com/65960235/82906439-d6274f80-9f97-11ea-99d8-c549b64eba87.png)
> 也不知道是哪儿的问题，就是启动不起来，麻烦大神帮忙指导一下谢谢

你肯定是在前端添加节点的时候将端口节点设置为443了，更改一下，然后重新启动soga就可以了。
