### ISSUE TITLE
v2board节点经常变红

### ISSUE THREAD

**Issue by Tenderness-Miao** [sprov065/soga#52]
节点信息上报间隔为10分钟，每次上报后节点状态会变为蓝色，大约一分钟后变为红色。

已联系v2board维护人员，告知v2board新版已更改流量上报方式，soga后端的上报可能存在问题，请这面排查一下，谢谢。

后端版本：2.2.2

**Comment by sprov065** [comment]
是你自己设置的上报间隔太长，前端觉得掉线了而已

**Comment by Tenderness-Miao** [comment]
> 是你自己设置的上报间隔太长，前端觉得掉线了而已

我这里手动设置的10分钟上报间隔，上次提issue的时候，你给我答复说，默认上报间隔是1个小时

**Comment by sprov065** [comment]
什么时候说一小时了，1分钟，不看文档的吗

**Comment by Tenderness-Miao** [comment]
> 什么时候说一小时了，1分钟，不看文档的吗

行，问题原因找到了。特么的被哪个小逼崽子坑了
