### ISSUE TITLE
sspanel 面板去除流量记录功能后，soga 上报流量出错

### ISSUE THREAD

**Issue by JH2628** [sprov065/soga#53]
https://github.com/Anankke/SSPanel-Uim/commit/5f9e33ea2ce5515bb61bcae4e953338322af1c84

日志错误提示：
Error 1146: Table '数据库名.user_traffic_log' doesn't exist

连接功能正常，不会影响正常连网

**Comment by sprov065** [comment]
这个等sspanel大改完毕之后一起更新
