### ISSUE TITLE
最新soga启动报错，v2ray和trojan节点都是

### ISSUE THREAD

**Issue by gimgoo** [sprov065/soga#56]
如题，arm架构的机器，使用最新版soga启动报错
`Parse node failed: invalid character 'e' looking for beginning of value
Jun 10 23:24:40 arm soga[25664]: 2021/06/10 23:24:40 error code: 1020
Jun 10 23:24:40 arm soga[25664]: 2021/06/10 23:24:40 get node failed: invalid character 'e' looking for beginning of value`

看着log也不知道什么情况，节点都是像x86那样配置的参数，望大佬指点指点。

**Comment by sprov065** [comment]
这个日志跟soga无关，网站问题
