### ISSUE TITLE
ProxyPanel的两个名词的区分

### ISSUE THREAD

**Issue by Andy-Chuck** [sprov065/soga#57]
连接端口和服务端口分别指什么端口？

我目前需要进行v2ray+nginx反代，分别设置了连接端口和服务端口，但是似乎只有服务端口有效。在ProxyPanel前台和soga日志中均只体现了服务端口，而在VnetPanel中，该功能正常。

![soga日志](https://user-images.githubusercontent.com/54295429/125607533-9667c8a7-8503-4a1e-b69d-717e379a69da.png)
soga日志
***
![pp前台](https://user-images.githubusercontent.com/54295429/125607539-1de2d71a-f115-42d8-97dd-589844dc46a5.png)
ProxyPanel前台
***
![pp后台](https://user-images.githubusercontent.com/54295429/125607545-ae738990-b1a8-4ca7-8520-c42edb3f19ca.png)
ProxyPanel后台

**Comment by sprov065** [comment]
后端只关心服务端口，连接端口的含义可以认为是订阅下发的端口，至于为何 ProxyPanel 显示服务端口，请去问 ProxyPanel 的开发者
