### ISSUE TITLE
最新版的Soga使用trojan问题

### ISSUE THREAD

**Issue by ssdsl0126** [sprov065/soga#58]
![image](https://user-images.githubusercontent.com/35905829/125887549-0baf757b-8cde-4afb-a206-85b800ef6439.png)
![image](https://user-images.githubusercontent.com/35905829/125887602-30de58b9-37b0-45a3-8624-767bd8b696b8.png)
面板是：proxypanel
使用：trojan
日志输出验证失败，不清楚什么问题，而且已经开启TLS了，怎么启动trojan还提示no ssl的

**Comment by sprov065** [comment]
重新安装即可
