### ISSUE TITLE
端口佔用

### ISSUE THREAD

**Issue by yusimtin** [sprov065/soga#6]
ws+tls需要使用443端口，ws需要使用80端口
但是寶塔https已經使用了443端口和80端口
請問應該怎麼解決？

**Comment by bbs3223474** [comment]
很麻烦，Trojan本身的工作原理就是类似于Nginx，所以它会尝试占用443端口去响应域名请求，于是就会和Nginx等程序冲突。也不是没有解决方案，参见：https://www.chengxiaobai.cn/record/trojan-shared-443-port-scheme.html。
但是Soga本身并不提供像原版Trojan那样的配置方式，没法完成设置“local_port”，已经尝试过在SSPanel-Uim中设置端口偏移，但并不能成功。在开发者解决这个问题之前，可能没办法共用。

**Comment by sprov065** [comment]
最简单的方式是使用其它端口，没有人规定一定要用 443 和 80 端口，也没有任何证据表明使用其它端口有什么问题
