### ISSUE TITLE
soga 启动失败

### ISSUE THREAD

**Issue by hotket** [sprov065/soga#60]
sspanel 按照前端设置了节点，后端填写好了v2ray参数，ws+tls,也配置了申请证书http模式，dnspod验证，soga无法启动
 2021/07/26 20:43:36 soga v2.5.2
Jul 26 20:43:36 racknerd-5d77e8 soga[2467]: 2021/07/26 20:43:36 read config file: /etc/soga/soga.conf
Jul 26 20:43:36 racknerd-5d77e8 soga[2467]: 2021/07/26 20:43:36 load blockList success, rule num: 0
Jul 26 20:43:36 racknerd-5d77e8 soga[2467]: 2021/07/26 20:43:36 load dns.yml success: 0
Jul 26 20:43:36 racknerd-5d77e8 soga[2467]: 2021/07/26 20:43:36 load routes.toml success, routes: 0, enable: true
Jul 26 20:43:36 racknerd-5d77e8 soga[2467]: 2021/07/26 20:43:36 is docker: false
Jul 26 20:43:36 racknerd-5d77e8 soga[2467]: 2021/07/26 20:43:36 Get node failed: {"ret":0,"data":"Token or IP is invalid. Now, your IP address is 23.94.208.14"}
Jul 26 20:43:36 racknerd-5d77e8 soga[2467]: 2021/07/26 20:43:36 get node failed: json: cannot unmarshal string into Go struct field F9LkhJlx.data of type DMuU3M87.J0p5Ss4c
Jul 26 20:43:36 racknerd-5d77e8 systemd[1]: soga.service: main process exited, code=exited, status=255/n/a
Jul 26 20:43:36 racknerd-5d77e8 systemd[1]: Unit soga.service entered failed state.
Jul 26 20:43:36 racknerd-5d77e8 systemd[1]: soga.service failed.
Jul 26 20:43:41 racknerd-5d77e8 systemd[1]: soga.service holdoff time over, scheduling restart.
Jul 26 20:43:41 racknerd-5d77e8 systemd[1]: Stopped soga Service.
Jul 26 20:43:41 racknerd-5d77e8 systemd[1]: start request repeated too quickly for soga.service
Jul 26 20:43:41 racknerd-5d77e8 systemd[1]: Failed to start soga Service.
Jul 26 20:43:41 racknerd-5d77e8 systemd[1]: Unit soga.service entered failed state.
Jul 26 20:43:41 racknerd-5d77e8 systemd[1]: soga.service failed.

**Comment by sprov065** [comment]
日志写得相当清楚

**Comment by hotket** [comment]
前端的第一项IP可以设置成域名吗？因为域名改动IP毕竟方便些
