### ISSUE TITLE
有计划加入SSR吗

### ISSUE THREAD

**Issue by sdfsdfsdf145314364** [sprov065/soga#8]
现在机场其实大部分还是SSR，因为有隧道有IPLC，再就是SSR用起来是最方便的，生态也最完善，也最知名，另外现在墙越来越离谱，高端的机场，都不靠什么协议， 基本都IPLC了。
V2和trojan虽然是未来，但目前还是属于是少数派。

**Comment by sprov065** [comment]
ssr后端不是已经有很多开源的吗，有什么痛点要解决

**Comment by sdfsdfsdf145314364** [comment]
> ssr预设不是已经有很多开源的吗，有什么痛点要解决
ssr多用户目前只有python，这说是痛点吧，也算不上有什么痛点，但支持上肯定没错啦，毕竟是给机场用的后端不是吗，而且应该加上不算难吧。
